### ISSUE TITLE
gradlew build error when building for Godot 3.x

### ISSUE THREAD

**Issue by houfaru** [drtwisted/godot-google-play-games-services#5]
**Godot version:**

Godot 3.0.2

**OS/device including version:**

Linux Mint 17.2 x86_64

**Issue description:**

Hi,
is this module also for Godot 3.0.2?
I failed at ./gradlew build when using it for Godot 3.0.2

actually, I tried other modules:
- https://github.com/kloder-games/godot-gpgs
- https://github.com/Mavhod/GodotGPS
- https://github.com/FrogSquare/GodotGoogleService

but all failed at ./gradlew build but with different errors.

**Steps to reproduce:**
1. download https://github.com/drtwisted/godot-google-play-game-services/tree/master/godot_gpgs into modules
2. remove
\< meta-data 
          android:name="com.google.android.gms.games.APP_ID"
          android:value="\xxxxxxx" /\>
because i already have admob working
3. edit
 env.android_add_default_config("applicationId 'org.godotengine.mygame'") 

4. execute the following commands:
 cd ~/godot-3.0.2-stable
 scons platform=android target=release -j 4
 cd platform/android/java
 ./gradlew build
4. getting this error: 
https://prnt.sc/itm69z

Thanks

**Comment by drtwisted** [comment]
Does 2.1.x engine module compiles OK on the same system?

**Comment by houfaru** [comment]
Yes, at least for Godot 2.1, it was "build successful"

I couldn't even export template for godot 2.1.4 even without the module, idk why, but it's a different problem

I haven't tried to use it in a project yet, i need some more time to understand how it works first.

Is it somehow possible to get it to work with 3.0.2?

**Comment by drtwisted** [comment]
@houfaru , I actually am stuck with 2.x myself, since there's no GLES 2 support in 3.x yet. I will look into it as soon as I have time. Can't tell what can be the possible cause for this at the moment.

**Comment by houfaru** [comment]
alright

**Comment by drtwisted** [comment]
@houfaru Hello! I have just done a build against 3.0.2 sources and everything went just fine. Do you still have problems building the template?

**Comment by houfaru** [comment]
Hi, i've been experimenting with https://github.com/FrogSquare/GodotGoogleService
I can already export the templates for that module, but there is still other problems I want to work on related to it.
I guess, I'll test yours afterwards in any case.
you can close this issue if you want.
thanks

**Comment by drtwisted** [comment]
Ok, please, let me know about the results. I'll keep the issue open until then! @houfaru

**Comment by houfaru** [comment]
it seems that the problem is the same with the other module with me.
Maybe there is something in my project causing this(because it did not happen to you):
after scons file build.gradle contains
```
dependencies {
	compile 'com.android.support:support-v4:27.+'  // can be removed if minSdkVersion 16 and modify DownloadNotification.java & V14CustomNotification.java
	compile 'com.google.android.gms:play-services-ads:+'
	compile 'com.google.android.gms:play-services:11.0.4'
	
}
```
then, if I change it
```
dependencies {
	compile 'com.android.support:support-v4:27.+'  // can be removed if minSdkVersion 16 and modify DownloadNotification.java & V14CustomNotification.java
	compile 'com.google.android.gms:play-services-ads:11.0.4'
	compile 'com.google.android.gms:play-services:11.0.4'
	
}
```
**./gradlew build** works

Also, if you use google app signing, google will remove your sign from the apk and re-sign it with their managed certificate.
So you have to set up the correct sha-1 on https://console.developers.google.com with the one provided by google. Not the sha-1 from your keystore that you use to to sign the apk

**Comment by houfaru** [comment]
hi @drtwisted 
by the way, it seems that your module is more extensive, i'm currently thinking about synchronization between locally stored score and the one uploaded to google. I've been searching the internet to write the method myself but so far no luck. I need to get the player's score from google play(using e.g. https://stackoverflow.com/questions/18115615/android-game-api-leaderboard-get-specific-player-score#18116206), but again ./gradlew build failed at this point(cannot find symbol ...loadPlayerCenteredScores). Did you happen to come across this problem when you wrote this module? Is it possible for you to write another method for this?

thanks

**Comment by drtwisted** [comment]
Regarding dependency change, it may totally be the issue and in majority of cases it is the reason of the failed build. Unfortunatly, ~~I can't give any other recomandations on that (but reading through fail output) , since each environment is quite unique.~~ Take a look at the UPD section.

Regarding the **loadPlayerCenteredScores** method wrapper for the module.

Firstly, No I can't make my own implementation, since there's no direct access to any APIs, all the module does (and any person using GPGS on Android) is using the public methods of Google's library.

Secondly, I'll check what can be done with current state of things in the module. If I'll be able to get a working code, than you'll definetly see an update in the repo. But I'm not sure about it since Google has marked classes the module currently uses as obsolete (That might be the cause of your cannot find symbol issue). So there's a need of rewrite of some parts with the new classes usage. That will be in some point in future.

**UPD:** Your constant build problems should be an issue of missing SDK packages.

I have just made a test implementation of loadPlayerCenteredScores and the build went fine! I was able to retreive data successfully!

Here are the screenshots of my SDK setup (Check your SDK manager in Android Studio):
***SDK Platforms***
![SDK Platforms](https://i.imgur.com/vsWqPAC.png)
***SDK Tools***
![SDK Tools](https://i.imgur.com/EWRmOOm.png)

**Comment by houfaru** [comment]
This module https://github.com/FrogSquare/GodotGoogleService works for me now,
the main difference seems to be that it's using GoogleSignInClient instead of GoogleApiClient
I don't really know why, but maybe it is indeed SDK problem for your module in my environment, because I don't have that many things installed for it:

**SDK Platform**
![sdkplatform](https://user-images.githubusercontent.com/10180151/38149078-70e55154-3459-11e8-9122-c61618b7cc6f.png)
**SDK tools**
![sdktools](https://user-images.githubusercontent.com/10180151/38149081-736cadfa-3459-11e8-8c82-7efbbda6011b.png)

I also tried to make my own implementation for the centered score. It also works fine. It looks like this:

```
public void loadCenteredScores(String l_id){
		Log.d("PlayGames", "loadingCenteredScore");

		mLeaderboardsClient.loadPlayerCenteredScores(l_id,LeaderboardVariant.TIME_SPAN_ALL_TIME, LeaderboardVariant.COLLECTION_PUBLIC, 1).addOnCompleteListener(new OnCompleteListener<AnnotatedData<LeaderboardsClient.LeaderboardScores>>(){

			public void onComplete(Task<AnnotatedData<LeaderboardsClient.LeaderboardScores>> scoreResults){
				AnnotatedData<LeaderboardsClient.LeaderboardScores> result=scoreResults.getResult();
				LeaderboardsClient.LeaderboardScores lbScores=result.get();
				LeaderboardScoreBuffer scoreBuffer=lbScores.getScores();
				Iterator<LeaderboardScore> it = scoreBuffer.iterator();
				long myScore=0;
				
                            	while(it.hasNext()){
                                	LeaderboardScore temp = it.next();
                                	Log.d("PlayGames", "player"+temp.getScoreHolderDisplayName()+" id:"+temp.getRawScore() + " Rank: "+temp.getRank());
					if(displayName.equals(temp.getScoreHolderDisplayName())){
						myScore=temp.getRawScore();							
					}


                            	}	
				GodotLib.calldeferred(instance_id, "_onLoadCenteredScoresComplete", new Object[]{(int)myScore});
				scoreBuffer.release();
				
			}
		});
	}
```

**Comment by houfaru** [comment]
oh wait, it seems i'm getting not-up-to-date centered score. when i load the leaderboard, i get 72, but when i load the centered score, i get 35. for the score submission, i'm using "submitScoreImmediate". did it happen to you?

**Comment by drtwisted** [comment]
I'm really surprised by the fact that you even have something built, since official Godot documentation on building your own Android templates states you need to have ALL SDK TOOLS INSTALLED in order to have no problems (which seem to have encountered for the reason).

Regarding different backend usage, I've already mensioned that Google has "changed the rules". Current backend is declared to be depricated and module needs to be rewritten to use the new tools Google encorage to use.

As for the discussion of leaderboard data retrieval I have no means to properly test which data exactly is retrieved atm, unfortunatly. Anyhow I reckon it goes beyond the scope of current issue and any further discussion of score retrieval in this topic is inapropriate. So for the sake of consistancy I would ask you to close this issue if you have no problems building the module (taking in to account that you need to install all SDK Platform tools and stuff as is said in Godot documentation, see above).

You can contact me in any other way convenient to you, if need be.

**Comment by houfaru** [comment]
Alright, thank you for your responsiveness
